pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'mvn clean install'
            }
        }
        stage('Test'){
              steps{
                sh 'mvn test'
            }
        }
         stage('Deploy'){
              steps{
                echo "simulando un despliegue a un servidor de aplicaciones"
            }
        }
    }

    post{
        always{
            echo "Siempre se ejecuta"
        }
        success{
            echo "Se ejecuta si todo se ejecuta correctamente"
        }
        failure{
            echo "Se ejecuta si algo anda mal"
        }
    }
}